// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/sgokul961/echo-hub-auth-svc/pkg/api"
	"github.com/sgokul961/echo-hub-auth-svc/pkg/api/handler"
	"github.com/sgokul961/echo-hub-auth-svc/pkg/config"
	"github.com/sgokul961/echo-hub-auth-svc/pkg/db"
	"github.com/sgokul961/echo-hub-auth-svc/pkg/repository"
	"github.com/sgokul961/echo-hub-auth-svc/pkg/usecase"
)

// Injectors from wire.go:

func InitApi(cfg config.Config) (*api.ServerHTTP, error) {
	gormDB, err := db.Init(cfg)
	if err != nil {
		return nil, err
	}
	userRepo := repository.NewUserRepo(gormDB)
	userUseCase := usecase.NewUserUseCase(userRepo, cfg)
	adminRepo := repository.NewAdminRepo(gormDB)
	adminUseCase := usecase.NewAdminUseCse(adminRepo, userRepo, cfg)
	userHandler := handler.NewUserHandler(userUseCase, adminUseCase)
	serverHTTP := api.NewServerHttp(userHandler)
	return serverHTTP, nil
}
